---
apiVersion: v1
kind: Service
metadata:
  name: matter-server-lb
  namespace: home-assistant
  annotations:
    io.cilium/lb-ipam-ips: "10.152.16.53"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: matter-server
    app.kubernetes.io/instance: matter-server
  ports:
    - name: websocket
      protocol: TCP
      port: 5580
      targetPort: 5580
