---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt-lb
  namespace: home-assistant
  annotations:
    io.cilium/lb-ipam-ips: "10.151.14.130"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mosquitto-mqtt
    app.kubernetes.io/instance: mosquitto-mqtt
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
