---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bunkerweb-mgmt
resources:
  - namespace.yaml
  - mariadb.yaml
  - secret.sops.yaml
  - release.yaml
  # certificates and ingress-route should be in cluster overlays
  # configmap is cluster-specific and should be in cluster overlays
