apiVersion: v1
kind: Secret
metadata:
  name: bunkerwebmgmt-secret
  namespace: bunkerweb-mgmt
stringData:
  LETS_ENCRYPT_DNS_CREDENTIAL_ITEM: ENC[AES256_GCM,data:/kdoWqe8dWKP06jlu1l6X0tETmjeSHdrkwXSUbB7caHAN8v5I0quow9zoQBNv2Truyre891eMsiy9ELapg==,iv:b51s2g+wS1yVPWjDp2pO33/hT1TPIKmsLVu6XGGib38=,tag:mf1+UmE2QoaFy2efKc8RWQ==,type:str]
  EMAIL_LETS_ENCRYPT: ENC[AES256_GCM,data:JMHDO4TwjFezaK1BgZ4GxiU=,iv:/fliIDA409guNvF/cG20TZk/65k6wUyKVDViUisD/Vw=,tag:hFmkKlHkGGXZZ3Ju7tiLAg==,type:str]
  DATABASE_URI: ENC[AES256_GCM,data:HZscmCPWMfa9deKWzNwNgpZnyYc+EgiDZf5oEc/u+L8fUHY6Itpf/hWRte3czpcMRZJl3q2cH3/y2s1DK4IcdgSv/j73nDH4ueWNW5LEaFpterJVOSAsmRrZ,iv:WXdcRKqAvz6zLBKL/MTNWJHUsTRgd3rcs2dKvaJDyXo=,tag:4Gkbt4RPK1dpwciN1rLn9A==,type:str]
  DB_ROOT_PASSWORD: ENC[AES256_GCM,data:dVjGVSyH9mLHlIJdUuo8akpyLnqvp//GsJCyzI9cuoSwxGPUjtknnIA84YhN+ejHkuT2rElCBG9NK+ecxyWGoQ==,iv:XyNszKOsn/TmMWLBIUokdsF1aQsl0EannVNcwZU3Bzw=,tag:yc5u1hGi22Mzbip44gPGJQ==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:FQk5mAOqKy7m+5NaOicyBBA9NWAZlyrN/y9HtVM0Si8=,iv:U9I+bqJkRkQM4+OUq39BMr1dJra+z5SqLRcD9q59s7A=,tag:nPQf7GJpyOXgRKBtZjf9lw==,type:str]
  TOTP_SECRETS: ENC[AES256_GCM,data:goHPv+Jz3nniMc3H1RNbhrNNxVaCWjEcpkDPviBCB5g=,iv:HmNrcBNDCur22ipCwkPRyle6FdoIDH8RdHS5XVtTxwg=,tag:6MZcjoOFvnGJSm17dKNt5Q==,type:str]
  ADMIN_USERNAME: ENC[AES256_GCM,data:vuekTmMI,iv:66sdU2/KXWmR8rItMCxsdeiUb5MWiDUSQKirsQVTJI8=,tag:BHG7j3VCGbUTY0lYEWSbwA==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:5FBKr+vTBC45dU9Thl0KGRBb68YWbxQpO5VTTIEGPaM=,iv:uy//J04seuBuvdbAYKnTYX0vykP43TgwcERumCBxvpI=,tag:u2UmTafTXviiMdSFNrTmzA==,type:str]
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:4k44XN4NMci3tKowcewzSzMhDuKZKDc7h3LYLdjCEDRIulYRjiTzE1dawm3IjxgMtpCY7wmPKzGk6+V7xBo/OZqAMm+Ld4I4VMTX3TWqhrFw/ysiejYi5dr5Sys3kDK5lo1dLC+pxrhA4SfVpUetlYuDiYDevHqakQ==,iv:Rwat6Sot7vbjOEHIGbUpym2IlSk5JCubvDuIRsU4BiE=,tag:VdxglQiXCDetxbcZQOgIgA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNlc2QTFvcURqSGEzWGI4
        d2NhT0pZR25oY1JnSUI4a29XaDR2UWlXKzFzCmtvbW0zMFk1RDcrUnIvY0JKdFVn
        cUFnZnVMMnd2SGNuWlh3cGw3UmkySkUKLS0tIGwzKzVBMFhJQkhlQWYyUjBsQllt
        NTZaaStRTlpSbDR4MlV0NHFjUFNkY1EKL2yo9VXxl6WC0u3/Fq40DMTONlui93pi
        KhuCl9wQ3P3IDWma0HObc97Z0YbFFOFKHRLOJotSHIPOs6gWZSbxMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T10:11:14Z"
  mac: ENC[AES256_GCM,data:E6C+teEMIouVbxpTo0QOpMtfmMU+gdBecmq1EgC3jXJ7FNJ9TrkToa6jokigY9NL0M9izJe6NEdm8MCUNDGZv4mjOVu7eLEr8rkBO64oMB0hkad1f4pPLC3mGVHgxylPx3Xi+6MF61RgdO3qRlH1pOK/TRHfK0rF4ZpkUCV4rgA=,iv:AgNf3if9zPECZIrfSHJqEodhf7RshSSijLpln0fssUY=,tag:bJ/L0z92ISpc733aFwH9RQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
