apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: bunkerweb-user
  namespace: bunkerweb-mgmt
spec:
  mariaDbRef:
    name: bunkerwebmgmt-mariadb
  name: bunkerweb
  passwordSecretKeyRef:
    name: bunkerwebmgmt-secret
    key: DB_PASSWORD
  maxUserConnections: 100
  host: "%"
  cleanupPolicy: Delete
  retryInterval: 5s
