apiVersion: v1
kind: Secret
metadata:
  name: discord-bot
  namespace: discord
stringData:
  TOKEN: ENC[AES256_GCM,data:dT0b6vfDtSXi2pClmKBzLdjFGyDUUhSyI5Lp0ZDKy2x5nnDB8XOBdZdhewRcR/gjnEqkCD9PuiIKVkO/MWkzDTa0HtZfpg==,iv:o8ax3o3zVEgRv22KbCVI1QEBh92IGQ6O2BGyz21NRoM=,tag:Ptag06/NvkUh8afh3jFbJw==,type:str]
  AZURE_TENANT_ID: ENC[AES256_GCM,data:VMg5dqjok2vrw1CIsOFpN8JMxD9e+hzZJpKnpg79ltpDBKgn,iv:el4a20yOal5n4riyURDYFKNcdXFkvIUXlAd89yFbftg=,tag:rFGmebHYrBdzjxP6px2/TA==,type:str]
  AZURE_CLIENT_ID: ENC[AES256_GCM,data:HBILuUXDwXR+8tXeWifFIGebeQGoJLvYnEJi6Ozk7JheD4ns,iv:rgw+CqitFEx7dsM8CaHk3rwb0ssRQY36oI3DJwaY8hg=,tag:80xvny9DZe4qc6LwJdckkw==,type:str]
  AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:4MKrobf13RcvgRETuI/UTWUpjVApkpVLQ624OwpPI/34jHDyTUo+sw==,iv:2ZQlw8sOCqUC0PlhwocLrdX/CsdlmHfnbB5rfGap8cc=,tag:s+VgcD7nAPWPOn8KGTTIUQ==,type:str]
  AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:U0QLEfVnU2twLWkF7ij3JOvAsWLWj8kEJaIAmi0mZ7vjXukF,iv:HttYDoHq1uuHquZzfhEQlmMV56vkAMmYRB9SMrnVXFA=,tag:TjZGXx0ZX88gMyn2Oj0hMA==,type:str]
  PTERODACTYL_BASE_URL: ENC[AES256_GCM,data:LH5qQXIT7Nev/H0DfL+ntyNWhKb9RgmJ0DJ5NPn6JQ==,iv:YT75dp7EGpVdL3T3dX1lCX4UD4vuVNvK8xY5xFn1bnk=,tag:MdcFt8a/3LbILwvtCgacEA==,type:str]
  PTERODACTYL_TOKEN: ENC[AES256_GCM,data:wyBImqkzK0dNDb0ccyX6SavyF357pIetJCxYkZWD/VVuOaXEC/ZqdguESbfo3HWT,iv:VdxjPjbVcc4sTA1gz/HAIYyO5G7MhtI/Og/HJRvrJBQ=,tag:qXkIphUXXuUvRiQJWC+QDQ==,type:str]
  APPLICATIONINSIGHTS_CONNECTIONSTRING: ENC[AES256_GCM,data:sPnipBj2fbuVY6s3PbsX4SGcZ2yKKuPGYaAAQVmch6P3f+ypx3p+gwGEvi7tihYkZkU0Lh5GgNL+FfttgTMosP9Cb6w/xFyExoPy+a0/RnbYEzxV7kXejxHwLueXKZNWK95W/1KcZ3pOJn+QjScIMRA9bd9bnfeIHmbGxCCZkxs1hcExvl57SOT1KF9yHoZqsOj75OoKfRnGkikDFcgIMv282/EXZSCfAgQBu41UiCZUsc3jZTPxaS7asSGAIEQPs2v21DfAprUw0P4kZHcy2O9KmlgRWNW76Jm7bB89cUrv/4NB0fIwyQrRuVZoM6oY,iv:Yij0AQ7S+IRafDpdZ7jp3QKBaYFPdpY9hgLc7zpIg5U=,tag:rGdi2HAoX54E81v7UFyoOQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TXoxUVY2M2JOeHFVdEhL
        T29ud0pMdVBDWDVDVXEzNWlPV1NvRit2RjM4CjVaRFNMdWZiRG5ib1ZPdy9NZzRF
        aDVjWGk1QkhITmNDeG5ySzJnSzZFNWcKLS0tIDBZVWJYMTRDS0xKaENjcnA1eU9X
        THBSUkhvS2Y4bnVGTnlDcU5YN3RRTXMKWlvl/dKy0zEYL+wCiXcB9cK/B/h1xvDg
        cI9D2qUdHbchF7N8A+dauhcHdC8hkfyWQdIJoSE4cUZMHHv/53Bfpw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-06T10:48:41Z"
  mac: ENC[AES256_GCM,data:TBqZQQCLAKtsQPktLlC7DJdE1jTCl2YjkqrHtpQfjGIv1w05BtWkT4/G6z18NhS//1CXPBKGf2T4Y79dayEmIqDfs8rmC462Grzr2ewWeEUPKQFLP+B0dmZbDSKLDPkj9clBLdI3cZq8ItZoSPBuR4q/Niu1/yf2K5b2wNXZlxQ=,iv:eRPguvy0+GzxqPboEeA9/WtQH4lLg1nsnkurGf2gQ4o=,tag:qeyExQIvppBzPayLwB4R3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
