apiVersion: v1
kind: Secret
metadata:
  name: discord-bot
  namespace: discord
stringData:
  TOKEN: ENC[AES256_GCM,data:F8+TUid2GdbBV2QAf1sMBOPYEzPz/iKAVHZu06U/9RP9rt6fIW2aK5d+ovZ+e8LMDip0c2vi/tQl6KAX1I+VUQV97zAYuQ==,iv:/HXYb186Mn3NO95ITYCUvf+8UwiVYN9YlbijMXH1/aY=,tag:v0i2IPEBEo04ZetccWm5Mw==,type:str]
  AZURE_TENANT_ID: ENC[AES256_GCM,data:gbDMPMOm6E1lOrqTWvhwRdbOiq2O9afRg0sDsbivP7TSyp7s,iv:cKEVkBcR/LGfMntTg1kqHwWnwLU6I7ObKThS4O+ezQU=,tag:QqPI5WRR5PW2AVLrLSvp+w==,type:str]
  AZURE_CLIENT_ID: ENC[AES256_GCM,data:lDhQns30DBKZZQlo6bPK+C6uLGA6EzJj/N3tBeCx5If5PqTO,iv:zs6MIUI1DABxuAb5YMgYQShTXve1RAM9abqE8JEOIWk=,tag:E8vExQ8JygP89NwTY64ECA==,type:str]
  AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:in0/J9IiPOKnUbWcgUQ3pZozt6fx+SfTk4FG+b3Q7ZNWF4I/2zmckw==,iv:aLXKpWpMvRzAmC40Hggk6NEjjYXctWEZJKvT7AdrJ8c=,tag:eNIkGNmfaTGFyaWjnrfGnA==,type:str]
  AZURE_SUBSCRIPTION_ID: ENC[AES256_GCM,data:XtcAx1aaAIC3fo2ChG6f/IgRDQnl9+VG29ZWIrhvCNJASr/T,iv:guZs7jZnNaLl4bKazoIr+Z5VYInAa4X283mX27UOBIs=,tag:z/pztgsOLUDKhL4zeu10VA==,type:str]
  PTERODACTYL_BASE_URL: ENC[AES256_GCM,data:lruJqO7VNYQd9xeJLFUk7JM6Dt+27tS07deMsn4eCHaSwpE=,iv:qTZCFd3nUN0HCMXLaq8YtuAnIf4wx8f6MNHy+mAw2Ic=,tag:B6y/LvvMH2vrI/Xy9hzOXQ==,type:str]
  PTERODACTYL_TOKEN: ENC[AES256_GCM,data:Ii25rZ+rm1jbV9zDZVUeypDOhUL6YRT0apdT05uXWBI+e0d6/IfOzq+eWx4xT5HU,iv:LLSHJRRSiQcUN5+TB45EITz1hZnkxqvPKH9Lj6EdiCc=,tag:91ukFaphn9iFREEGe55knQ==,type:str]
  APPLICATIONINSIGHTS_CONNECTIONSTRING: ENC[AES256_GCM,data:f8L3sis9dr0qiJuhQT1fH26t4O1U2qokzyJ2aQrsKYkr1SpjgZsHBykXxPlhtAmqGJbSNBvacXIFDtZ6gK6cfCkDGw+TnC2bZcjG/h5gaxwCEADEQmo84+PlyUDAhWyktAbVmEwizpvT4Vk6mgIPDKE7wzVUFi8WvfZKLcGRqia33TawYy81kB1QwDDXI7SwTIJ1wmi+Dvfgi9K9SvLFSR2P9WU1lRHFmlJhsr4ERx6E2c9PiAkBL3Wyc7mIkyzTOU3rJ9w4+DRCIh/mKdv331lYUwBjiA1O7NtVdU6QCHOIRaBdB5v3f5PNOPicfs9B,iv:ym1T3tNxj75OG11FMiX81bcHjA4twutla76rUU5JvOY=,tag:4s8mmg/tivo149PJYEZONw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZk96MkgvYVlVcm9mT3g0
        SmZpOHEzWlZFVkxVVUJpR2VwQXhGWXdBUFVBCkx1VGpsKzFyaE9RR1RVc2p4L3cr
        dll5ZmZTQ3RwbUc2OWxCVEswR3ZJb00KLS0tIE10QVE3TTBlYW94UmZ1ZWdtT2lL
        MStSR0l0V1dsWVNJVllHcUpMc0dTeDAK5G5tkNlXGVVXrTEr26AqHrRtHV4dxiup
        +BWfR1kkpTXkkD/K6BMpTx+AytadU8XZxhAV1wxPw1sAbt6hv9KmxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T00:02:31Z"
  mac: ENC[AES256_GCM,data:GVNNWNsJgx1AcnOnsKac9X0d00N5zUmgunyWuGG1b/jtCSyifuBzI1LrNv7JLsYArD3bq9mty0BoxBftOIR0Fw8h3RYPucJAGd1TNWchCAFQmSJgdhWAPW+o3TgHDCb4PFAjxCSw2qddO87cf+/TM5ziFRzJLRLSpUdrXQyqSFo=,iv:4l1V4sCY+84PQHKP3IhxgwwuzWS8ZeaiCMIESFteQ8U=,tag:ke8jG7V7cVqHWOB9CPBWwA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
