---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-staging-tls
  namespace: jellyfin
spec:
  secretName: jellyfin-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "jellyfin.wanda.bancey.xyz"
  dnsNames:
    - "jellyfin.wanda.bancey.xyz"
    - "jellyfin.bancey.xyz"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: jellyfin
spec:
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "jellyfin.wanda.bancey.xyz"
  dnsNames:
    - "jellyfin.wanda.bancey.xyz"
    - "jellyfin.bancey.xyz"
