apiVersion: v1
kind: Secret
metadata:
  name: plex-keystore-secret
  namespace: plex
stringData:
  password: ENC[AES256_GCM,data:be1iC4C7pruPcpA0DNDwUvyuzQ==,iv:ddH9dM9nYZRz2V0uJQQOI+iXKpRKebh6foOY8lporYg=,tag:HoiOSi8uWK972o6FCjtL0g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTk5FUmxLc1AxRkhyaEFz
        b0pEVC85ZVZGSDI2QmhEbEtQQ3htZU5BYURzCkFWT2cxOWJhTE9VQ1Y3RWR5UHNM
        eFVwaS9Oc2l6cERsVEpkYWhlOXFIY0EKLS0tIHlMMmlOSnlHc1cyRk0xdExvUFFJ
        a2hTTzRvVFRERGtvdGF5Y1JTZkJFaXMKJjcIdddYmuf4L2wL55EoLQfdEL8SOn0D
        gbnkMsvCsqjrPtorooEceUfTzYP5dLxZIepnlE8E1m6x1rqHJX1dPg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T20:52:20Z"
  mac: ENC[AES256_GCM,data:Ymiu6P2vmKyWHf6V0Vm4ZPNABXEBbD41XqFKMU9InDhO1tLR7oH+1eVWRsn8veRPOpnJ7bDsba+FfWWt8ZdX7gzGmlA9BGWrhAdr/OA/kYGy4t6iPQmNxd+iU26TNC2a9OrzJ3LVJRT2f/MKVTOKKlfgR1Lt5Ndcaxf7B7Z6RUM=,iv:jerNihVZnECE8yvJ2ugb9G/IL0cxHx8ES4X+iG/iPxc=,tag:fWXSgyND/dFbfHOLsUCNhw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
