apiVersion: v1
kind: Secret
metadata:
  name: plex-keystore-secret
  namespace: plex
stringData:
  password: ENC[AES256_GCM,data:oZI78KffJGayoJN5C3+Lnvau,iv:7GjzBOb2kk5d1oeQEstsA/rMCW+UQMNiqrm74SEBM5o=,tag:g2EBPzq5U2Jj+vz0vU5XHw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m604fu0zt3dnypzq4nasx63mzzzcx49dxngwe7aj8vr0x8pm63jqfsjuyq
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYWRkZTQreGtYb0pLamhj
        OVdDMTV2RmYreWpoUmx4V1FUWlN3SUhhTnhBCjlMV2dkZVE2SmZsQUJKSFZkVC8w
        YkY0WWEwaitHRHdISENtMnd3RlBNcDgKLS0tIGY3QjBDK3JRQ2xYVUgxRlFOZTNN
        ak1qcmFWVk1Xem5FT3VDWUkwNnBEV2sKmXXqh0eOwn9ATWrOJmxJKm9lcV8d2FXk
        4JMfbaHhpGuwQnNo1sPKhOf5zfZiim8QHAhGfuBUjCjXaehWkvPyJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T11:10:29Z"
  mac: ENC[AES256_GCM,data:rwNYK7+DBQlA+WmtoBTk7ORKkJMZygizBJXbmfuDkx0RTxHT1U5xwNasOzoYnLHcER69XvdVm8OQ/OioxI6sc9YS8QpAri5Oa4RKhrX3M59cF0SuKY6TZDKYDppDpvLu8rMBQ1ObjTiSrcnEkNOM8WU+TgsSwD6oppxP9cJpsZw=,iv:IsEviCQ+q1r9ArT9cnyuH2hRx+13aGbp6uoMh0T2SSs=,tag:Xj7E+71QLLaleVDWkoOCMg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
