---
collections:
  - name: kubernetes.core
    version: 6.2.0
  - name: ansible.utils
    version: 6.0.1
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.3.0
roles:
  - name: xanmanning.k3s
    version: v3.6.2
